### ISSUE TITLE
support for android

### ISSUE THREAD

**Issue by lammermann** [woboq/qmetaobject-rs#51]
Hi,
I would like to use this for a cross platform GUI. Is it possible to use this crate for mobile platforms like android? Are there any special quirks necessary to make it compile and to deploy it?

Thanks in advance

**Comment by Stuv7CB** [comment]
Hello, I'm not developer of this library but I have build my app as apk for android.
First of all one should add [.cargo/config](https://doc.rust-lang.org/cargo/reference/config.html) with paths to ar and linker from android ndk e.g.
```toml
[target.armv7-linux-androideabi]
ar = "/home/leonid/Android/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ar"
linker = "/home/leonid/Android/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi22-clang"
```
and one should add in one's $PATH path to qmake for android and set enviroment variable for
`CXX` to appropriate android compiler from ndk, because otherwise `cxx` crate wouldn't be able to build `qmetaobject` targeting android.
Also set output as cdylib and add function with following signature
```rust
#[no_mangle]
pub extern fn main(argc: i32, argv: *mut *mut i8) -> i32
```
After compiling source code to .so library you can create library with this https://doc.qt.io/qt-5/deployment-android.html
I don't find better way to produce apk from .so file than using this https://github.com/LaurentGomila/qt-android-cmake 

If there is any better way to produce apk file I would like to know it.
